import { PHASE_PRODUCTION_BUILD } from "next/dist/shared/lib/constants";
import SideNavBar from "./components/sidebar";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-gray-100 h-dvh w-full pb-10">
        <SideNavBar />
        {children}
      </body>
    </html>
  );
}
